# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tps_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tps_message.proto',
  package='',
  serialized_pb='\n\x11tps_message.proto\"7\n\x11\x43S_RPC_RunRequest\x12\x0e\n\x06opcode\x18\x01 \x02(\r\x12\x12\n\nparameters\x18\x02 \x01(\x0c\"7\n\x11SC_RPC_RunRequest\x12\x0e\n\x06opcode\x18\x01 \x02(\r\x12\x12\n\nparameters\x18\x02 \x01(\x0c\"]\n\nActionData\x12\x11\n\taction_id\x18\x01 \x02(\r\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x02(\r\x12\x11\n\tplayer_id\x18\x03 \x02(\t\x12\x14\n\x0c\x61\x63tion_param\x18\x04 \x02(\x0c\"C\n\x10\x43S_Fight_Message\x12\r\n\x05\x66rame\x18\x01 \x02(\r\x12 \n\x0b\x61\x63tion_data\x18\x02 \x02(\x0b\x32\x0b.ActionData\"C\n\x10SC_Fight_Message\x12\r\n\x05\x66rame\x18\x01 \x02(\r\x12 \n\x0b\x61\x63tion_list\x18\x02 \x03(\x0b\x32\x0b.ActionData')




_CS_RPC_RUNREQUEST = _descriptor.Descriptor(
  name='CS_RPC_RunRequest',
  full_name='CS_RPC_RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opcode', full_name='CS_RPC_RunRequest.opcode', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='CS_RPC_RunRequest.parameters', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=76,
)


_SC_RPC_RUNREQUEST = _descriptor.Descriptor(
  name='SC_RPC_RunRequest',
  full_name='SC_RPC_RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opcode', full_name='SC_RPC_RunRequest.opcode', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='SC_RPC_RunRequest.parameters', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=133,
)


_ACTIONDATA = _descriptor.Descriptor(
  name='ActionData',
  full_name='ActionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_id', full_name='ActionData.action_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_type', full_name='ActionData.action_type', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='ActionData.player_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_param', full_name='ActionData.action_param', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=228,
)


_CS_FIGHT_MESSAGE = _descriptor.Descriptor(
  name='CS_Fight_Message',
  full_name='CS_Fight_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='CS_Fight_Message.frame', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_data', full_name='CS_Fight_Message.action_data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=230,
  serialized_end=297,
)


_SC_FIGHT_MESSAGE = _descriptor.Descriptor(
  name='SC_Fight_Message',
  full_name='SC_Fight_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='SC_Fight_Message.frame', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_list', full_name='SC_Fight_Message.action_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=299,
  serialized_end=366,
)

_CS_FIGHT_MESSAGE.fields_by_name['action_data'].message_type = _ACTIONDATA
_SC_FIGHT_MESSAGE.fields_by_name['action_list'].message_type = _ACTIONDATA
DESCRIPTOR.message_types_by_name['CS_RPC_RunRequest'] = _CS_RPC_RUNREQUEST
DESCRIPTOR.message_types_by_name['SC_RPC_RunRequest'] = _SC_RPC_RUNREQUEST
DESCRIPTOR.message_types_by_name['ActionData'] = _ACTIONDATA
DESCRIPTOR.message_types_by_name['CS_Fight_Message'] = _CS_FIGHT_MESSAGE
DESCRIPTOR.message_types_by_name['SC_Fight_Message'] = _SC_FIGHT_MESSAGE

class CS_RPC_RunRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CS_RPC_RUNREQUEST

  # @@protoc_insertion_point(class_scope:CS_RPC_RunRequest)

class SC_RPC_RunRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SC_RPC_RUNREQUEST

  # @@protoc_insertion_point(class_scope:SC_RPC_RunRequest)

class ActionData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIONDATA

  # @@protoc_insertion_point(class_scope:ActionData)

class CS_Fight_Message(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CS_FIGHT_MESSAGE

  # @@protoc_insertion_point(class_scope:CS_Fight_Message)

class SC_Fight_Message(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SC_FIGHT_MESSAGE

  # @@protoc_insertion_point(class_scope:SC_Fight_Message)


# @@protoc_insertion_point(module_scope)
